version: 1
formatters:
  default:
    format: "%(asctime)s %(name)s %(funcName)s [%(levelname)s]: %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stdout
  # file:
  #   class: logging.FileHandler
  #   formatter: default
  #   filename: log
loggers:
  root:
    level: INFO
    handlers: [console]
    propagate: yes
