name: Setup Python
description: Install Python and dependencies with poetry
inputs:
  python-version:
    required: false
    default: 3.9
runs:
  using: composite
  steps:
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install poetry
      run: python -m pip install poetry

    - name: install dependencies
      run: poetry install
