name: Python CI
on:
  push:

jobs:
  RunFlake8:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: ./.github/actions/setup-poetry
      - name: Run flake8
        run: poetry run flake8 .

  RunIsort:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: ./.github/actions/setup-poetry
      - name: Run isort
        run: poetry run isort **/*.py -c

  RunBlack:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: ./.github/actions/setup-poetry
      - name: Run black
        run: poetry run black . --check

  RunMypy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: ./.github/actions/setup-poetry
      - name: Run mypy
        run: poetry run mypy .

  RunUnitTest:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: ./.github/actions/setup-poetry
      - name: Run unit test
        run: poetry run pytest -m unit --cov
