name: Python lint and unit tests
on:
  push:

jobs:
  RunFlake8:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        uses: ./.github/actions/setup-poetry

      - name: run flake8
        run: poetry run flake8 .

  RunIsort:
    runs-on: ubuntu-latest
    container:
      image: python:3.9-buster
    timeout-minutes: 20
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: |
          pip install -U pip && pip install poetry
          poetry config virtualenvs.create false
          poetry install

      - name: run isort
        run: isort **/*.py -c

  RunBlack:
    runs-on: ubuntu-latest
    container:
      image: python:3.9-buster
    timeout-minutes: 20
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: |
          pip install -U pip && pip install poetry
          poetry config virtualenvs.create false
          poetry install

      - name: run black
        run: black . --check

  RunMypy:
    runs-on: ubuntu-latest
    container:
      image: python:3.9-buster
    timeout-minutes: 20
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: |
          pip install -U pip && pip install poetry
          poetry config virtualenvs.create false
          poetry install

      - name: run mypy
        run: mypy .

  RunUnitTest:
    runs-on: ubuntu-latest
    container:
      image: python:3.9-buster
    timeout-minutes: 20
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v2

      - name: install dependencies
        run: |
          pip install -U pip && pip install poetry
          poetry config virtualenvs.create false
          poetry install

      - name: run unit test
        id: run_test
        run: pytest -m unit --cov
