name: Python CI
on:
  push:

jobs:
  Lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install poetry and dependencies
        run: python -m pip install pre-commit

      - name: Lint
        run: pre-commit run --all-files

  UnitTest:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install poetry and dependencies
        run: python -m pip install poetry && poetry install

      - name: Run unit test
        run: poetry run pytest -m unit --cov
